### ISSUE TITLE
Migrate to Epoxy v4

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/MoonShot#30]
The latest release of Epoxy supports incremental annotation processing. Migrate the app to [Epoxy v4](https://github.com/airbnb/epoxy/releases/tag/4.0.0) to benefit from faster compilation times.

**Comment by mrwhoknows55** [comment]
@haroldadmin I would like to work on this issue. Do you expect any issues after updating epoxy to v4?

**Comment by haroldadmin** [comment]
I am not sure, I haven't been following the changelog very closely. Its quite likely though, as MoonShot uses Epoxy extensively.

**Comment by mrwhoknows55** [comment]
what are your suggestions on same?

**Comment by haroldadmin** [comment]
A good place to start is to increment the version number of the dependency, and then sync + rebuild the project. Look out for any compilation errors or new warnings.

**Comment by mrwhoknows55** [comment]
thank you @haroldadmin . I'll open PR once hacktoberfest starts ✌

**Comment by mrwhoknows55** [comment]
thanks @haroldadmin  for assigning it to me. It worked fine after updating the dependency version to 4.0.0 from Versions.kt file from buildSrc module. Is this right?

**Comment by haroldadmin** [comment]
Yes, that should do it. If there were no compilation errors or additional warnings, please go ahead with the pull request.
